<a href="https://colab.research.google.com/github/aditya01-dev/Deep-Learning/blob/main/01_Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation="relu"),
    Dense(64, activation="relu"),
    Dense(10, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(x_train, y_train, epochs=5, batch_size=32)

test_loss, test_accuracy = model.evaluate(x_test, y_test)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

predictions = model.predict(x_test)

print("Predicted Class:", predictions[0].argmax())
print("Actual Class:", y_test[0])

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9293 - loss: 0.2395
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9694 - loss: 0.1009
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9776 - loss: 0.0716
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9833 - loss: 0.0532
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9858 - loss: 0.0434
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9769 - loss: 0.0732
Test Loss: 0.07323011755943298
Test Accuracy: 0.9768999814987183
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Predicted Class: 7
Actual Class: 7


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

x = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype=float)

y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=float)

model = Sequential([
    Dense(4, input_dim=2, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(x, y, epochs=1000, verbose=0)

loss, accuracy = model.evaluate(x, y, verbose=0)

print("Final Loss:", loss)
print("Final Accuracy:", accuracy)

prediction = model.predict(x)

print("Predictions:")
print(prediction)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Final Loss: 0.2867942154407501
Final Accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Predictions:
[[0.28297248]
 [0.7572981 ]
 [0.81554693]
 [0.28297248]]


In [ ]:
import numpy as np

x = np.array([1, -1, 1])
w = np.array([0.0, 0.0, 0.0])
target = 1
learning_rate = 0.1

print("Initial Weights:", w)

for i in range(5):
    output = np.dot(x, w)
    w = w + learning_rate * target * x
    print("\nIteration", i + 1)
    print("Output:", output)
    print("Updated Weights:", w)

print("\nFinal Weights:", w)

Initial Weights: [0. 0. 0.]

Iteration 1
Output: 0.0
Updated Weights: [ 0.1 -0.1  0.1]

Iteration 2
Output: 0.30000000000000004
Updated Weights: [ 0.2 -0.2  0.2]

Iteration 3
Output: 0.6000000000000001
Updated Weights: [ 0.3 -0.3  0.3]

Iteration 4
Output: 0.9000000000000001
Updated Weights: [ 0.4 -0.4  0.4]

Iteration 5
Output: 1.2000000000000002
Updated Weights: [ 0.5 -0.5  0.5]

Final Weights: [ 0.5 -0.5  0.5]


In [4]:
import numpy as np

x = np.array([1, 2, 3, 4], dtype=float)
y = np.array([2, 4, 6, 8], dtype=float)

w = 0.0
b = 0.0
learning_rate = 0.01
epochs = 100

n = len(x)

for epoch in range(epochs):
    y_pred = w * x + b

    error = y - y_pred

    dw = -(2 / n) * np.sum(x * error)
    db = -(2 / n) * np.sum(error)

    w = w - learning_rate * dw
    b = b - learning_rate * db

    if (epoch + 1) % 10 == 0:
        loss = np.mean(error ** 2)
        print(f"Epoch {epoch+1}, Loss = {loss:.4f}, Weight = {w:.4f}, Bias = {b:.4f}")

print("\nFinal Weight:", w)
print("Final Bias:", b)

print("\nPredictions:")
for i in range(n):
    print(f"Input = {x[i]}, Predicted = {w*x[i]+b:.2f}, Actual = {y[i]}")

Epoch 10, Loss = 1.1751, Weight = 1.5104, Bias = 0.4936
Epoch 20, Loss = 0.0843, Weight = 1.7583, Bias = 0.5584
Epoch 30, Loss = 0.0529, Weight = 1.8030, Bias = 0.5547
Epoch 40, Loss = 0.0492, Weight = 1.8149, Bias = 0.5404
Epoch 50, Loss = 0.0463, Weight = 1.8213, Bias = 0.5248
Epoch 60, Loss = 0.0436, Weight = 1.8267, Bias = 0.5093
Epoch 70, Loss = 0.0410, Weight = 1.8319, Bias = 0.4943
Epoch 80, Loss = 0.0387, Weight = 1.8369, Bias = 0.4797
Epoch 90, Loss = 0.0364, Weight = 1.8417, Bias = 0.4655
Epoch 100, Loss = 0.0343, Weight = 1.8463, Bias = 0.4518

Final Weight: 1.846347367319157
Final Bias: 0.45175740934344377

Predictions:
Input = 1.0, Predicted = 2.30, Actual = 2.0
Input = 2.0, Predicted = 4.14, Actual = 4.0
Input = 3.0, Predicted = 5.99, Actual = 6.0
Input = 4.0, Predicted = 7.84, Actual = 8.0


In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical

iris = load_iris()

X = iris.data
y = iris.target

y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=8,
    verbose=1
)

loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

predictions = model.predict(X_test)

print("Predicted Classes:")
print(predictions.argmax(axis=1))

print("Actual Classes:")
print(y_test.argmax(axis=1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.0667 - loss: 1.2609
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1750 - loss: 1.1633
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3583 - loss: 1.0828
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4250 - loss: 1.0209
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.4500 - loss: 0.9705
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4750 - loss: 0.9275
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.8891
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5750 - loss: 0.8520
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6417 - loss: 0.8178
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6667 - loss: 0.7871 
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7167 - loss: 0.7569
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - a

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype=float)

Y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=float)

model = Sequential([
    Dense(4, input_dim=2, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X,
    Y,
    epochs=1000,
    verbose=1
)

loss, accuracy = model.evaluate(X, Y, verbose=0)

print("Final Loss:", loss)
print("Final Accuracy:", accuracy)

predictions = model.predict(X)

print("\nPredicted Output:")
print(predictions)

print("\nRounded Predictions:")
print(np.round(predictions))

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.7262
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.2500 - loss: 0.7255
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.2500 - loss: 0.7249
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.2500 - loss: 0.7243
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.2500 - loss: 0.7237
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.2500 - loss: 0.7231
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.2500 - loss: 0.7225
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 0.7219
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.2500 - loss: 0.7213
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.2500 - loss: 0.7207
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.2500 - loss: 0.7202
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accura

Final Loss: 0.08219713717699051
Final Accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step

Predicted Output:
[[0.22076873]
 [0.9766758 ]
 [0.98098725]
 [0.03588515]]

Rounded Predictions:
[[0.]
 [1.]
 [1.]
 [0.]]
